apiVersion: v1 
kind: pod 
metadata: 
  name: my-pod 
  labels: 
    app: my-app 
    version: v1 
spec:   
  containers: 
    - name: my-container 
      image: nginx:latest 
      ports: 
        - containerPort: 80 
---
apiVersion: v1 
kind: Service 
metadata: 
  name: my-service 
spec: 
  type: ClusterIP/NodePort/LoadBalancer  # type: LoadBalancer for external access, NodePort for internal, ClusterIP for internal only  
  selector: 
    app: my-app
  ports:  
    - protocol: TCP
      port: 80
      targetPort: 8080 
...
# This YAML file defines a pod and a service in Kubernetes. 
# The pod runs an Nginx container, while the service exposes the pod to other services or external traffic.